export type Article = {
  id: number;
  title: string;
  keyword: string;
  traffic: string;
  words: number;
  createdOn: string;
  status: string;
};

export const articles: Article[] = [
  {
    id: 1,
    title: "How to Improve Your Skills in League of Legends",
    keyword: "league of legends",
    traffic: "2240000",
    words: 4515,
    createdOn: "20 hours ago",
    status: "generated",
  },
  {
    id: 2,
    title: "How to Master Last Hitting in League of Legends",
    keyword: "league of legends",
    traffic: "2240000",
    words: 3480,
    createdOn: "21 hours ago",
    status: "generated",
  },
  {
    id: 3,
    title: "7 Tips for Better Teamplay in League of Legends",
    keyword: "league of legends",
    traffic: "2240000",
    words: 2676,
    createdOn: "a day ago",
    status: "generated",
  },
  {
    id: 4,
    title: "Top Virtual Executive Assistant Services (2024)",
    keyword: "virtual executive assistant",
    traffic: "2900",
    words: 2408,
    createdOn: "1 Oct 24",
    status: "generated",
  },
  {
    id: 5,
    title: "Unlimited Graphics Design Solutions",
    keyword: "unlimited graphic design services",
    traffic: "3510",
    words: 1793,
    createdOn: "",
    status: "generated",
  },
  {
    id: 6,
    title: "Top Amazon Payment Methods for Quick Access to Funds",
    keyword: "amazon payment methods",
    traffic: "3600",
    words: 2647,
    createdOn: "",
    status: "generated",
  },
  {
    id: 7,
    title:
      "Backlinks 101: What are backlinks and why they're important [Free template]",
    keyword: "backlinks",
    traffic: "8100",
    words: 2291,
    createdOn: "",
    status: "generated",
  },
  {
    id: 8,
    title: "7 Leading AI SEO Tools in 2024 (Ranked & Compared)",
    keyword: "ai seo software",
    traffic: "1870",
    words: 1543,
    createdOn: "--",
    status: "generated",
  },
  {
    id: 9,
    title: "Unlimited Graphic Design Services You Can Rely On",
    keyword: "unlimited graphic design services",
    traffic: "3510",
    words: 1214,
    createdOn: "",
    status: "generated",
  },
  // Additional dummy data
  {
    id: 10,
    title: "Ultimate Guide to Freelance Digital Marketing in 2024",
    keyword: "freelance digital marketing",
    traffic: "9200",
    words: 3120,
    createdOn: "2 days ago",
    status: "generated",
  },
  {
    id: 11,
    title: "Best Online Coding Bootcamps for Beginners (2024 Edition)",
    keyword: "online coding bootcamp",
    traffic: "6800",
    words: 3985,
    createdOn: "3 days ago",
    status: "generated",
  },
  {
    id: 12,
    title: "How to Start a Dropshipping Business in 2024",
    keyword: "dropshipping business",
    traffic: "15200",
    words: 4278,
    createdOn: "4 days ago",
    status: "generated",
  },
  {
    id: 13,
    title: "Top 10 Productivity Tools for Remote Teams",
    keyword: "remote productivity tools",
    traffic: "4700",
    words: 2780,
    createdOn: "5 days ago",
    status: "generated",
  },
  {
    id: 14,
    title: "AI Content Writing Tools: Which One Should You Choose?",
    keyword: "ai content writing",
    traffic: "5200",
    words: 1895,
    createdOn: "6 days ago",
    status: "generated",
  },
  {
    id: 15,
    title: "Mastering Technical SEO in 2024",
    keyword: "technical seo",
    traffic: "6100",
    words: 3430,
    createdOn: "7 days ago",
    status: "generated",
  },
  {
    id: 16,
    title: "The Beginner's Guide to WordPress SEO",
    keyword: "wordpress seo",
    traffic: "7300",
    words: 2765,
    createdOn: "8 days ago",
    status: "generated",
  },
  {
    id: 17,
    title: "How to Monetize a Blog in 2024",
    keyword: "monetize blog",
    traffic: "10500",
    words: 3540,
    createdOn: "9 days ago",
    status: "generated",
  },
  {
    id: 18,
    title: "Best Practices for Email Marketing Campaigns",
    keyword: "email marketing",
    traffic: "8700",
    words: 3102,
    createdOn: "10 days ago",
    status: "generated",
  },
  {
    id: 19,
    title: "Content Calendar Tools to Streamline Your Workflow",
    keyword: "content calendar tools",
    traffic: "2600",
    words: 2040,
    createdOn: "11 days ago",
    status: "generated",
  },
  {
    id: 20,
    title: "Understanding Google E-E-A-T for SEO Success",
    keyword: "google eeat",
    traffic: "6400",
    words: 2954,
    createdOn: "12 days ago",
    status: "generated",
  },
  {
    id: 21,
    title: "Top Instagram Marketing Strategies That Work",
    keyword: "instagram marketing",
    traffic: "13300",
    words: 3880,
    createdOn: "13 days ago",
    status: "generated",
  },
  {
    id: 22,
    title: "How to Create an Effective Landing Page",
    keyword: "landing page optimization",
    traffic: "4100",
    words: 2210,
    createdOn: "14 days ago",
    status: "generated",
  },
  {
    id: 23,
    title: "The Rise of Voice Search and What It Means for SEO",
    keyword: "voice search seo",
    traffic: "5600",
    words: 2893,
    createdOn: "15 days ago",
    status: "generated",
  },
  {
    id: 24,
    title: "Understanding GA4: What You Need to Know",
    keyword: "google analytics 4",
    traffic: "7000",
    words: 3412,
    createdOn: "16 days ago",
    status: "generated",
  },
  {
    id: 25,
    title: "Why Local SEO Matters More Than Ever",
    keyword: "local seo",
    traffic: "9100",
    words: 2736,
    createdOn: "17 days ago",
    status: "generated",
  },
  {
    id: 26,
    title: "What is Programmatic Advertising? A Beginner’s Guide",
    keyword: "programmatic advertising",
    traffic: "4200",
    words: 3125,
    createdOn: "18 days ago",
    status: "generated",
  },
  {
    id: 27,
    title: "Top YouTube SEO Techniques to Boost Your Channel",
    keyword: "youtube seo",
    traffic: "11200",
    words: 2650,
    createdOn: "19 days ago",
    status: "generated",
  },
  {
    id: 28,
    title: "How to Write High-Converting Copy for Landing Pages",
    keyword: "copywriting tips",
    traffic: "6500",
    words: 2380,
    createdOn: "20 days ago",
    status: "generated",
  },
  {
    id: 29,
    title: "Best Practices for Internal Linking in 2024",
    keyword: "internal linking",
    traffic: "5100",
    words: 1980,
    createdOn: "21 days ago",
    status: "generated",
  },
  {
    id: 30,
    title: "7 Ways to Repurpose Blog Content for More Traffic",
    keyword: "repurpose content",
    traffic: "3200",
    words: 2175,
    createdOn: "22 days ago",
    status: "generated",
  },
  {
    id: 31,
    title: "The Power of Long-Form Content in SEO Strategy",
    keyword: "long form content",
    traffic: "4600",
    words: 3420,
    createdOn: "23 days ago",
    status: "generated",
  },
  {
    id: 32,
    title: "How to Use Reddit for Market Research",
    keyword: "reddit market research",
    traffic: "2800",
    words: 1730,
    createdOn: "24 days ago",
    status: "generated",
  },
  {
    id: 33,
    title: "Top SaaS Marketing Trends to Watch in 2024",
    keyword: "saas marketing",
    traffic: "5800",
    words: 2900,
    createdOn: "25 days ago",
    status: "generated",
  },
  {
    id: 34,
    title: "AI Writing Tools vs Human Writers: Pros and Cons",
    keyword: "ai writing tools",
    traffic: "7600",
    words: 3250,
    createdOn: "26 days ago",
    status: "generated",
  },
  {
    id: 35,
    title: "How to Use Schema Markup to Boost SEO",
    keyword: "schema markup",
    traffic: "4400",
    words: 2480,
    createdOn: "27 days ago",
    status: "generated",
  },
];
